### ISSUE TITLE
Package `mpd` does not exist

### ISSUE THREAD

**Issue by cpiber** [felipemarinho97/musnify-mpd#3]
Did you mean `python-mpd2`? This package seems to have the same interface, but could also be `python-mpd`...

**Comment by felipemarinho97** [comment]
Well, this package existed 5 years ago.. maybe it's `python-mpd2`, but I really don't know. Most dependencies were from python2 at the time.
But... there is no need to support python2 anymore. So, if python-mpd2 is working well, I think it's the best candidate to install.

**Comment by cpiber** [comment]
I also can't find `mpd` for python2 interestingly... There is an old, unsupported `python-mpd`, which `python-mpd2` tries to replace. I used `python-mpd2` and it ran fine.
