### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by bonelifer** [felipemarinho97/musnify-mpd#5]
I have my config file setup as below, but no covers are shown.  Xubuntu 20.04, python3.8. Also this code suggests to me an icon is supposed to be included? Instead I get the dreaded red X.  Also not good with regex, does that regex only look for cover.jpg or does it also look at Cover.jpg

`            self.notification.update("MPD Stopped",icon="music")`
```
[mpd]
host = 192.168.1.80
port = 6600

# This is where musnify-mpd will look for searching the local album covers.
musiclibrary = /media/william/Data2/BACKUP/MP3/
#

[apiKey]
# If you want to fetch the album covers from LastFm,
# enable this option and provide a apiKey.
# You can get you apiKey here: https://www.last.fm/api/account/create
#
# lastfm = YOUR_LASTFM_API_KEY

```

**Comment by felipemarinho97** [comment]
Yes, the icon with alias `music` is supposed to be included in your system icons, most distros will show a generic music icon. The regex for finding local covers will match everything that starts with album, cover, folder, front and has the image formats: gif, jpeg, jpg, png
